[package]
name = "rift_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
rift_core = { path = "../rift_core" }
font-kit = "0.14.2"
tokio = { version = "1.41.0", features = ["full"] }
anyhow = "1.0"
