name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: rt,re
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            bin: rt
          - target: aarch64-apple-darwin
            os: macos-latest
            bin: rt,re
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: rt,re
          - target: x86_64-apple-darwin
            os: macos-latest
            bin: rt,re
          - target: universal-apple-darwin
            os: macos-latest
            bin: rt,re
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Disable local cargo config for Linux
        if: runner.os == 'Linux'
        run: |
          if [ -f .cargo/config.toml ]; then mv .cargo/config.toml .cargo/config.toml.ci.bak; fi
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libfontconfig-dev libasound2-dev
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: rift-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
